-- ============================================
-- This is generated by claude.ai
-- ============================================


-- ============================================
-- SEED DATA FOR SWEDISH REAL ESTATE DATABASE
-- ============================================

-- Lookup tables (redan inkluderade i din schema)
-- property_types, tenures, listing_status, price_types, media_types, open_house_types

-- ============================================
-- LOCATIONS
-- ============================================
INSERT INTO locations (street_address, postal_code, city, municipality, county, country, latitude, longitude) VALUES
('Storgatan 12', '11436', 'Stockholm', 'Stockholm', 'Stockholms län', 'Sverige', 59.334591, 18.063240),
('Kungsgatan 45 lgh 1201', '41119', 'Göteborg', 'Göteborg', 'Västra Götalands län', 'Sverige', 57.703850, 11.965540),
('Västra Hamngatan 8', '21137', 'Malmö', 'Malmö', 'Skåne län', 'Sverige', 55.604980, 13.003820),
('Skogsvägen 23', '75642', 'Uppsala', 'Uppsala', 'Uppsala län', 'Sverige', 59.858560, 17.638930),
('Havsutsiktsvägen 5', '26139', 'Landskrona', 'Landskrona', 'Skåne län', 'Sverige', 55.870800, 12.830200),
('Björkallén 78', '90325', 'Umeå', 'Umeå', 'Västerbottens län', 'Sverige', 63.825840, 20.263030),
('Strandpromenaden 3', '39230', 'Kalmar', 'Kalmar', 'Kalmar län', 'Sverige', 56.661530, 16.356710),
('Villavägen 15', '18262', 'Djursholm', 'Danderyd', 'Stockholms län', 'Sverige', 59.399120, 18.058430),
('Lantbruksvägen 1', '24735', 'Dalby', 'Lund', 'Skåne län', 'Sverige', 55.671390, 13.349780),
('Centralgatan 22 lgh 502', '65224', 'Karlstad', 'Karlstad', 'Värmlands län', 'Sverige', 59.379500, 13.504170),
('Norra Vallgatan 62', '21122', 'Malmö', 'Malmö', 'Skåne län', 'Sverige', 55.608920, 12.997540),
('Hammarby Allé 47', '12063', 'Stockholm', 'Stockholm', 'Stockholms län', 'Sverige', 59.303140, 18.094520),
('Kungsportsavenyen 31', '41136', 'Göteborg', 'Göteborg', 'Västra Götalands län', 'Sverige', 57.699420, 11.975890),
('Eriksbergsgatan 8B', '11430', 'Stockholm', 'Stockholm', 'Stockholms län', 'Sverige', 59.341230, 18.058760),
('Frejgatan 55', '11326', 'Stockholm', 'Stockholm', 'Stockholms län', 'Sverige', 59.345670, 18.051230);

-- ============================================
-- ADDRESSES (för användare)
-- ============================================
INSERT INTO addresses (street_address, postal_code, city, municipality, county, country) VALUES
('Odengatan 52', '11322', 'Stockholm', 'Stockholm', 'Stockholms län', 'Sverige'),
('Vasagatan 18', '41124', 'Göteborg', 'Göteborg', 'Västra Götalands län', 'Sverige'),
('Södra Förstadsgatan 4', '21143', 'Malmö', 'Malmö', 'Skåne län', 'Sverige'),
('Sveavägen 89', '11350', 'Stockholm', 'Stockholm', 'Stockholms län', 'Sverige'),
('Linnégatan 12', '41304', 'Göteborg', 'Göteborg', 'Västra Götalands län', 'Sverige'),
('Regementsgatan 28', '21747', 'Malmö', 'Malmö', 'Skåne län', 'Sverige'),
('Kungsholmsgatan 5', '11227', 'Stockholm', 'Stockholm', 'Stockholms län', 'Sverige'),
('Drottninggatan 55', '75310', 'Uppsala', 'Uppsala', 'Uppsala län', 'Sverige');

-- ============================================
-- USERS
-- ============================================
INSERT INTO users (email, password, first_name, last_name, phone, role_id, address_id) VALUES
('anna.lindqvist@email.se', '$2b$10$xJwL5v5z5z5z5z5z5z5z5u', 'Anna', 'Lindqvist', '070-123 45 67', NULL, 1),
('erik.johansson@email.se', '$2b$10$xJwL5v5z5z5z5z5z5z5z5u', 'Erik', 'Johansson', '073-234 56 78', NULL, 2),
('maria.andersson@email.se', '$2b$10$xJwL5v5z5z5z5z5z5z5z5u', 'Maria', 'Andersson', '076-345 67 89', NULL, 3),
('johan.nilsson@email.se', '$2b$10$xJwL5v5z5z5z5z5z5z5z5u', 'Johan', 'Nilsson', '070-456 78 90', NULL, 4),
('sara.bergström@email.se', '$2b$10$xJwL5v5z5z5z5z5z5z5z5u', 'Sara', 'Bergström', '073-567 89 01', NULL, 5),
('anders.svensson@email.se', '$2b$10$xJwL5v5z5z5z5z5z5z5z5u', 'Anders', 'Svensson', '076-678 90 12', NULL, 6),
('lisa.pettersson@email.se', '$2b$10$xJwL5v5z5z5z5z5z5z5z5u', 'Lisa', 'Pettersson', '070-789 01 23', NULL, 7),
('magnus.karlsson@email.se', '$2b$10$xJwL5v5z5z5z5z5z5z5z5u', 'Magnus', 'Karlsson', '073-890 12 34', NULL, 8),
('emma.olsson@email.se', '$2b$10$xJwL5v5z5z5z5z5z5z5z5u', 'Emma', 'Olsson', '076-901 23 45', NULL, NULL),
('peter.eriksson@email.se', '$2b$10$xJwL5v5z5z5z5z5z5z5z5u', 'Peter', 'Eriksson', '070-012 34 56', NULL, NULL),
('admin@fastighetsportal.se', '$2b$10$xJwL5v5z5z5z5z5z5z5z5u', 'Admin', 'Adminsson', '08-123 45 67', NULL, NULL);

-- ============================================
-- USER_ROLES
-- ============================================
INSERT INTO user_roles (name, user_id) VALUES
('buyer', 1),
('buyer', 2),
('seller', 3),
('seller', 4),
('agent', 5),
('agent', 6),
('agent', 7),
('agent', 8),
('buyer', 9),
('seller', 10),
('admin', 11);

-- ============================================
-- AGENCIES
-- ============================================
INSERT INTO agencies (name, org_number, phone, website) VALUES
('Fastighetsbyrån Stockholm', '556123-4567', '08-123 45 00', 'https://www.fastighetsbyran.se'),
('Svensk Fastighetsförmedling Göteborg', '556234-5678', '031-234 56 00', 'https://www.svenskfast.se'),
('Bjurfors Malmö', '556345-6789', '040-345 67 00', 'https://www.bjurfors.se'),
('Erik Olsson Fastighetsförmedling', '556456-7890', '08-456 78 00', 'https://www.erikolsson.se'),
('Länsförsäkringar Fastighetsförmedling', '556567-8901', '08-567 89 00', 'https://www.lansfast.se');

-- ============================================
-- AGENTS
-- ============================================
INSERT INTO agents (user_id, title, license_number, bio) VALUES
(5, 'Fastighetsmäklare', 'FM-2018-1234', 'Sara har över 10 års erfarenhet av bostadsförsäljning i Göteborgsområdet. Specialiserad på bostadsrätter i centrala lägen.'),
(6, 'Fastighetsmäklare', 'FM-2015-2345', 'Anders är en erfaren mäklare med fokus på villor och radhus i Malmöregionen. Känd för sin noggrannhet och personliga service.'),
(7, 'Fastighetsmäklare', 'FM-2019-3456', 'Lisa är specialiserad på exklusiva bostäder i Stockholms innerstad. Hon har en bakgrund inom arkitektur.'),
(8, 'Fastighetsmäklare', 'FM-2020-4567', 'Magnus har bred erfarenhet av alla typer av bostäder och är känd för sin kunskap om Uppsalamarknaden.');

-- ============================================
-- AGENT_AGENCIES
-- ============================================
INSERT INTO agent_agencies (agency_id, agent_id) VALUES
(2, 1),  -- Sara @ Svensk Fastighetsförmedling Göteborg
(3, 2),  -- Anders @ Bjurfors Malmö
(1, 3),  -- Lisa @ Fastighetsbyrån Stockholm
(4, 4);  -- Magnus @ Erik Olsson Fastighetsförmedling

-- ============================================
-- PROPERTIES
-- ============================================
INSERT INTO properties (location_id, property_type_id, tenure_id, year_built, living_area_sqm, additional_area_sqm, plot_area_sqm, rooms, floor, monthly_fee, energy_class) VALUES
(1, 1, 1, 1925, 78, 5, NULL, 3, 4, 4250, 'C'),
(2, 1, 1, 2018, 92, 8, NULL, 4, 12, 5100, 'A'),
(3, 1, 1, 1965, 65, NULL, NULL, 2.5, 2, 3200, 'D'),
(4, 2, 2, 1985, 145, 45, 850, 5, NULL, NULL, 'C'),
(5, 2, 2, 2020, 180, 30, 1200, 6, NULL, NULL, 'A'),
(6, 1, 1, 2010, 55, 3, NULL, 2, 5, 2800, 'B'),
(7, 3, 1, 2015, 120, 15, 150, 4, NULL, 3500, 'A'),
(8, 2, 2, 1935, 280, 80, 2500, 8, NULL, NULL, 'E'),
(9, 4, 2, 1990, 95, 20, 5000, 4, NULL, NULL, 'C'),
(10, 1, 1, 2005, 72, 5, NULL, 3, 5, 3850, 'B'),
(11, 1, 3, 1970, 58, NULL, NULL, 2, 3, 8500, 'D'),
(12, 1, 1, 2019, 85, 10, NULL, 3.5, 8, 4600, 'A'),
(13, 1, 1, 1910, 110, 15, NULL, 4, 3, 6200, 'C'),
(14, 1, 1, 2022, 45, NULL, NULL, 1.5, 6, 3100, 'A'),
(15, 1, 1, 1955, 88, 8, NULL, 3.5, 2, 4100, 'C');

-- ============================================
-- LISTINGS
-- ============================================
INSERT INTO listings (agent_id, title, description, status_id, list_price, price_type_id, published_at, expires_at, external_ref) VALUES
(3, 'Ljus 3:a på Storgatan - Östermalm', 'Fantastisk ljus lägenhet med originaldetaljer från 1920-talet. Högt i tak, vackra golv och öppen planlösning mellan kök och vardagsrum. Balkong mot innergård.', 2, 6950000, 1, '2025-05-15 10:00:00+02', '2025-08-15 23:59:59+02', 'HEM-2025-001'),
(1, 'Modern 4:a med fantastisk utsikt - Göteborg', 'Nyproducerad lägenhet på 12:e våningen med panoramautsikt över hamnen. Öppen planlösning, två badrum och stor balkong. Garage ingår.', 2, 5495000, 1, '2025-05-20 09:00:00+02', '2025-08-20 23:59:59+02', 'HEM-2025-002'),
(2, 'Charmig 2,5:a i Malmö centrum', 'Välskött lägenhet i populärt område nära allt. Renoverat kök och badrum. Förening med god ekonomi.', 2, 2295000, 1, '2025-05-22 11:00:00+02', '2025-08-22 23:59:59+02', 'HEM-2025-003'),
(4, 'Rymlig villa i Uppsala', 'Familjevänlig villa med stort trädgårdsland. Nytt tak 2020, renoverat badrum 2022. Nära skolor och kommunikationer.', 2, 5950000, 1, '2025-05-10 08:00:00+02', '2025-08-10 23:59:59+02', 'HEM-2025-004'),
(2, 'Exklusiv havsnära villa - Landskrona', 'Arkitektritad villa från 2020 med havsutsikt. Smart home-system, pool och carport för två bilar. Energiklass A.', 2, 12500000, 1, '2025-05-25 10:00:00+02', '2025-11-25 23:59:59+01', 'HEM-2025-005'),
(1, 'Prisvärd 2:a i Umeå', 'Perfekt för förstagångsköpare! Ljus och fräsch lägenhet med balkong mot söder. Låg månadsavgift.', 3, 1295000, 4, '2025-04-01 09:00:00+02', NULL, 'HEM-2025-006'),
(3, 'Modernt radhus i Kalmar', 'Energisnålt radhus med egen trädgård och carport. Öppen planlösning och genomgående hög standard.', 2, 3850000, 1, '2025-05-28 10:00:00+02', '2025-08-28 23:59:59+02', 'HEM-2025-007'),
(3, 'Sekelskiftesvilla - Djursholm', 'Magnifik sekelskiftesvilla med bevarade originaldetaljer. Stor tomt med äldre trädgård. Renoveringsbehov.', 1, 18900000, 1, NULL, NULL, 'HEM-2025-008'),
(2, 'Fritidshus nära Dalby', 'Charmigt fritidshus med stor tomt. Perfekt för den som söker lugn och ro nära naturen. Gästhus och bastu.', 2, 2450000, 1, '2025-05-18 11:00:00+02', '2025-08-18 23:59:59+02', 'HEM-2025-009'),
(4, 'Trevlig 3:a i Karlstad centrum', 'Ljus och välplanerad lägenhet i centralt läge. Balkong, hiss och förråd. Nyligen renoverad.', 2, 2195000, 1, '2025-05-27 09:00:00+02', '2025-08-27 23:59:59+02', 'HEM-2025-010'),
(2, 'Hyresrätt i Malmö - Möjlighet!', 'Välskött hyresrätt med chans till förstahandskontrakt. Centralt läge, balkong och nyrenoverat kök.', 2, 25000, 1, '2025-05-29 10:00:00+02', '2025-07-29 23:59:59+02', 'HEM-2025-011'),
(3, 'Nyproduktion Hammarby Sjöstad', 'Stilren 3,5:a i nytt miljöcertifierat hus. Balkong mot vattnet, genomgående lägenhet med kvällssol.', 2, 6250000, 1, '2025-05-30 08:00:00+02', '2025-08-30 23:59:59+02', 'HEM-2025-012'),
(1, 'Elegant våning på Avenyn', 'Representativ våning med anor. Stuckaturer, kakelugnar och parkettgolv. Balkong mot Avenyn.', 3, 8900000, 4, '2025-03-15 10:00:00+01', NULL, 'HEM-2025-013'),
(3, 'Compact living Eriksberg', 'Smart planerad etta/tvåa för dig som vill bo centralt. Inglasad balkong, tvättstuga i lägenheten.', 2, 3450000, 1, '2025-05-31 09:00:00+02', '2025-08-31 23:59:59+02', 'HEM-2025-014'),
(3, 'Klassisk 3,5:a Vasastan', 'Ljus hörnlägenhet med balkong i två väderstreck. Genomgående lägenhet, öppen spis i vardagsrummet.', 4, 5750000, 1, '2025-02-01 10:00:00+01', NULL, 'HEM-2025-015');

-- ============================================
-- LISTING_PROPERTIES
-- ============================================
INSERT INTO listing_properties (property_id, listing_id) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5),
(6, 6),
(7, 7),
(8, 8),
(9, 9),
(10, 10),
(11, 11),
(12, 12),
(13, 13),
(14, 14),
(15, 15);

-- ============================================
-- LISTING_AGENTS (ytterligare mäklare på objekt)
-- ============================================
INSERT INTO listing_agents (agent_id, listing_id) VALUES
(3, 1),
(1, 2),
(2, 3),
(4, 4),
(2, 5),
(1, 6),
(3, 7),
(3, 8),
(4, 8),  -- Två mäklare på exklusiva villan
(2, 9),
(4, 10),
(2, 11),
(3, 12),
(1, 13),
(3, 14),
(3, 15);

-- ============================================
-- SAVED_SEARCHES
-- ============================================
INSERT INTO saved_searches (user_id, name, send_email) VALUES
(1, 'Lägenheter Stockholm innerstad 3+ rum', TRUE),
(1, 'Villor Danderyd/Djursholm', FALSE),
(2, 'Bostadsrätter Göteborg max 4 mkr', TRUE),
(9, 'Alla nyproduktioner Stockholm', TRUE),
(10, 'Radhus Skåne', FALSE);

-- ============================================
-- SAVED_LISTINGS
-- ============================================
INSERT INTO saved_listings (user_id, listing_id) VALUES
(1, 1),
(1, 8),
(1, 12),
(2, 2),
(2, 13),
(9, 1),
(9, 12),
(9, 14),
(10, 4),
(10, 7);

-- ============================================
-- LISTING_MEDIA
-- ============================================
INSERT INTO listing_media (listing_id, media_type_id, url, caption, position) VALUES
-- Listing 1 - Storgatan
(1, 1, 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80', 'Fasad mot Storgatan', 1),
(1, 1, 'https://images.unsplash.com/photo-1505691723518-36a5ac3be353?auto=format&fit=crop&w=1400&q=80', 'Vardagsrum med öppen spis', 2),
(1, 1, 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80', 'Renoverat kök', 3),
(1, 1, 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1400&q=80', 'Master bedroom', 4),
(1, 2, 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1400&q=80', 'Planritning', 5),
(1, 3, 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1400&q=80', 'Virtuell visning', 6),

-- Listing 2 - Göteborg
(2, 1, 'https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&w=1200&q=80', 'Byggnaden från hamnsidan', 1),
(2, 1, 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80', 'Utsikt från balkong', 2),
(2, 1, 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1400&q=80', 'Vardagsrum', 3),
(2, 2, 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80', 'Planritning', 4),

-- Listing 3 - Malmö
(3, 1, 'https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&w=1200&q=80', 'Innergård', 1),
(3, 1, 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80', 'Vardagsrum', 2),
(3, 2, 'https://images.unsplash.com/photo-1505691723518-36a5ac3be353?auto=format&fit=crop&w=1400&q=80', 'Planritning', 3),

-- Listing 4 - Uppsala villa
(4, 1, 'https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&w=1200&q=80', 'Villan från gatan', 1),
(4, 1, 'https://images.unsplash.com/photo-1505691723518-36a5ac3be353?auto=format&fit=crop&w=1400&q=80', 'Trädgård', 2),
(4, 1, 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1400&q=80', 'Kök', 4),
(4, 2, 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1400&q=80', 'Planritning våning 1', 5),
(4, 2, 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1400&q=80', 'Planritning våning 2', 6),
(4, 3, 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1400&q=80', 'Drönarvideo', 7),

-- Listing 5 - Landskrona
(5, 1, 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1400&q=80', 'Villan från havet', 1),
(5, 1, 'https://images.unsplash.com/photo-1505691723518-36a5ac3be353?auto=format&fit=crop&w=1400&q=80', 'Pool och terrass', 2),
(5, 1, 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1400&q=80', 'Vardagsrum med havsutsikt', 3),
(5, 3, 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1400&q=80', '3D-visning', 4),

-- Listing 8 - Djursholm
(8, 1, 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1400&q=80', 'Huvudbyggnad', 1),
(8, 1, 'https://images.unsplash.com/photo-1505691723518-36a5ac3be353?auto=format&fit=crop&w=1400&q=80', 'Trädgårdssida', 2),
(8, 1, 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80', 'Entréhall', 3),
(8, 1, 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80', 'Salong', 4),
(8, 2, 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1400&q=80', 'Planritning', 5),

-- Listing 12 - Hammarby Sjöstad
(12, 1, 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1400&q=80', 'Nybyggt hus vid vattnet', 1),
(12, 1, 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80', 'Balkong mot sjön', 2),
(12, 1, 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1400&q=80', 'Vardagsrum', 3),
(12, 2, 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1400&q=80', 'Planritning', 4);

-- ============================================
-- OPEN_HOUSES
-- ============================================
INSERT INTO open_houses (listing_id, starts_at, ends_at, type_id, note) VALUES
-- Kommande visningar
(1, '2025-06-01 13:00:00+02', '2025-06-01 14:00:00+02', 1, 'Välkomna på visning! Anmälan ej nödvändig.'),
(1, '2025-06-02 18:00:00+02', '2025-06-02 19:00:00+02', 1, 'Kvällsvisning'),
(2, '2025-06-03 11:00:00+02', '2025-06-03 12:00:00+02', 1, NULL),
(3, '2025-06-01 12:00:00+02', '2025-06-01 13:00:00+02', 1, 'Drop-in visning'),
(4, '2025-06-02 10:00:00+02', '2025-06-02 11:30:00+02', 1, 'Visning av hela fastigheten inklusive trädgård'),
(5, '2025-06-08 14:00:00+02', '2025-06-08 15:30:00+02', 2, 'Bokad visning - kontakta mäklaren'),
(7, '2025-06-04 17:00:00+02', '2025-06-04 18:00:00+02', 1, NULL),
(10, '2025-06-05 12:00:00+02', '2025-06-05 13:00:00+02', 1, 'Lunch-visning'),
(12, '2025-06-07 11:00:00+02', '2025-06-07 12:00:00+02', 1, NULL),
(12, '2025-06-07 13:00:00+02', '2025-06-07 14:00:00+02', 1, 'Extra visning'),

-- Digitala visningar
(1, '2025-06-05 19:00:00+02', '2025-06-05 19:30:00+02', 3, 'Digital visning via Zoom - länk skickas efter anmälan'),
(5, '2025-06-10 18:00:00+02', '2025-06-10 19:00:00+02', 3, '3D-visning och Q&A med mäklaren'),
(8, '2025-06-15 10:00:00+02', '2025-06-15 11:00:00+02', 3, 'Exklusiv digital förhandsvisning');